apiVersion: v1
kind: Service
metadata:
  name: kubeproxy-frontend
  labels:
    app: kubeproxy
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http1-service
    targetPort: 3023
  - port: 443
    name: https1-service
    targetPort: 3024
  selector:
    app: kubeproxy
    tier: frontend