apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubeproxy-frontend
  labels:
    app: kubeproxy
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: kubeproxy
        tier: frontend
    spec:
      containers:
      - name: kubeproxy-app
        # Replace [GCLOUD_PROJECT] with your project ID or use `make template`.
        #image: gcr.io/fourth-scheme-192005/kubeproxy2
        image: gcr.io/glowforge-manufacturing/kubeproxy3
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3023
        - name: https-server
          containerPort: 3024
        #GF
        volumeMounts:
          - mountPath: /etc/ssl-glowforge
            name: ssl
            readOnly: true
          - mountPath: /etc/newrelic-secret
            name: secret-newrelic-volume
            readOnly: true
          - mountPath: /etc/secrets
            name: secret-volume
            readOnly: true
        #END GF
        env:
          - name: PROJECT_ID
            #value: fourth-scheme-192005
            value: glowforge-manufacturing
      #GF
      volumes:
        - name: ssl
          secret:
            defaultMode: 420
            secretName: manufacturing-ssl
        - hostPath:
            path: /etc/ssl/certs
          name: ssl-certs
        - name: secret-newrelic-volume
          secret:
            defaultMode: 420
            secretName: newrelic.yml
        - name: secret-volume
          secret:
            defaultMode: 420
            secretName: instance-secrets
      #END GF