apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubeproxy-frontend
  labels:
    app: kubeproxy
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: kubeproxy
        tier: frontend
    spec:
      containers:
      - name: kubeproxy-app
        # Replace [GCLOUD_PROJECT] with your project ID or use `make template`.
        #image: gcr.io/fourth-scheme-192005/kubeproxy2
        image: gcr.io/glowforge-manufacturing/kubeproxy3
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3023
        env:
          - name: PROJECT_ID
            #value: fourth-scheme-192005
            value: glowforge-manufacturing